### ISSUE TITLE
Code coverage w/ istanbul & wct

### ISSUE THREAD

**Issue by alessandro-aglietti** [growingabit/pwa-frontend#19]
Actually there isn't a simple and clean way to do code coverage on web components of Polymer 2.

So we leave this issue with links of blocking issues.

https://github.com/Polymer/web-component-tester/issues/61

https://github.com/thedeeno/web-component-tester-istanbul/issues/38

https://github.com/t2ym/web-component-tester/issues/1

**Comment by pietrovismara** [comment]
Fixed as we won't use Polymer.
