### ISSUE TITLE
SMS verification

### ISSUE THREAD

**Issue by aberonni** [growingabit/pwa-frontend#27]
**Steps to reproduce**
- Login
- Proceed SMS verification step
- Insert phone number
- Receive SMS

**Expected result**
A second input field appears after inserting the phone number, and the SMS contains a verification code.

**Actual result**
I receive a link via SMS.

**Comment by pietrovismara** [comment]
L'expected result è gia implementato in locale, aspetto conferma che la verifica del codice funziona  da @canemacchina o @gianmarcobrescia  per deployare
